# -*- coding: utf-8 -*-
"""Credit_Scoring_Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o9CRzlDxi6AZZDhS2qGpYZqYPf-5ncWw

#Importing Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score, roc_curve
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

"""# Load Dataset"""

df = pd.read_csv('credit_data.csv')
df.head()

df.info()

print('--------')

print(df.describe())

print(df.isnull().sum())

"""# Data Cleaning and Pre-Processing"""

df = df.drop(['ID', 'Customer_ID', 'Name', 'SSN'], axis = 1) # dropping irrelevant columns
display(df.head())

# Convert "Age" column to numeric, coercing errors
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

#Calculating median age
median_age = df['Age'].median()

# Defining outliers boundaries
lower_bound = 0
upper_bound = 100

# Replacing outliers with median age
df['Age'] = np.where((df['Age'] < lower_bound) | (df['Age'] > upper_bound), median_age, df['Age'])

# Impute missing values in 'Age' with the median
df['Age'] = df['Age'].fillna(median_age)

# Displaying updated age column information
display(df['Age'].describe())

# Replacing '_' with 'Unknown' in "Credi_Mix" Column
df['Credit_Mix'] = df['Credit_Mix'].str.replace('_', 'Unknown')
display(df['Credit_Mix'].value_counts())

# Fill missing values with a placeholder
df['Credit_History_Age'] = df['Credit_History_Age'].fillna('0 Years and 0 Months')

# Extracting years and month using string manipulation
df['Years'] = df['Credit_History_Age'].apply(lambda x: int(x.split(' ')[0]))
df['Months'] = df['Credit_History_Age'].apply(lambda x: int(x.split(' ')[3]))

# Converting years and months to total months
df['Credit_History_Age'] = df['Years'] * 12 + df['Months']

# Converting to numeric type
df['Credit_History_Age'] = pd.to_numeric(df['Credit_History_Age'])

# Dropping the temporary 'Years' and 'Months' columns
df.drop(['Years', 'Months'], axis=1, inplace=True)

# Displaying the first few rows and info to verify the changes
display(df.head())
display(df.isnull().sum())

# Handling missing values in "Type_of_Loan" by filling with 'Not Specified'
df['Type_of_Loan'] = df['Type_of_Loan'].fillna('Not Specified')

#Displaying updated 'Type_of_Loan' column information
display(df['Type_of_Loan'].value_counts())

# Getting all unique loan types
unique_loan_types = df['Type_of_Loan'].str.split(', ').explode().unique()

# Removing 'Not Specified' if it exists in the unique types
if 'Not Specified' in unique_loan_types:
    unique_loan_types = unique_loan_types[unique_loan_types != 'Not Specified']

# Creating binary columns for each unique loan type
for loan_type in unique_loan_types:
  df[loan_type.replace(' ', '_')] = df['Type_of_Loan'].apply(lambda x: 1 if loan_type in x else 0)

# Dropping the original 'Type_of_Loan' column
df.drop('Type_of_Loan', axis = 1, inplace = True)

# Displaying the first few rows of the updated DataFrame
display(df.head())

# Clean and convert specified numeric columns to numeric, coercing errors to NaN
cols_to_clean_and_convert = ['Monthly_Inhand_Salary', 'Num_of_Delayed_Payment', 'Num_Credit_Inquiries', 'Amount_invested_monthly', 'Monthly_Balance', 'Annual_Income', 'Changed_Credit_Limit', 'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Total_EMI_per_month', 'Num_of_Loan', 'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Delay_from_due_date']

for col in cols_to_clean_and_convert:
    if col in df.columns:
        if df[col].dtype == 'object':
            df[col] = df[col].astype(str).str.replace(r'[^\d.-]+', '', regex=True) # Remove non-numeric characters except decimals and hyphens
        df[col] = pd.to_numeric(df[col], errors='coerce') # Convert to numeric, coercing errors

# Calculate the median for each specified numeric column again (after cleaning)
median_monthly_inhand_salary = df['Monthly_Inhand_Salary'].median()
# Use mode for Num_of_Delayed_Payment as it might be count-like
mode_num_delayed_payment = df['Num_of_Delayed_Payment'].mode()[0]
median_num_credit_inquiries = df['Num_Credit_Inquiries'].median()
median_amount_invested_monthly = df['Amount_invested_monthly'].median()
median_monthly_balance = df['Monthly_Balance'].median()
median_annual_income = df['Annual_Income'].median()
median_changed_credit_limit = df['Changed_Credit_Limit'].median()
median_outstanding_debt = df['Outstanding_Debt'].median()
median_credit_utilization_ratio = df['Credit_Utilization_Ratio'].median()
median_total_emi_per_month = df['Total_EMI_per_month'].median()
median_num_of_loan = df['Num_of_Loan'].median()
median_num_bank_accounts = df['Num_Bank_Accounts'].median()
median_num_credit_card = df['Num_Credit_Card'].median()
median_interest_rate = df['Interest_Rate'].median()
median_delay_from_due_date = df['Delay_from_due_date'].median()


# Fill missing values in each column with its corresponding median/mode
df['Monthly_Inhand_Salary'] = df['Monthly_Inhand_Salary'].fillna(median_monthly_inhand_salary)
df['Num_of_Delayed_Payment'] = df['Num_of_Delayed_Payment'].fillna(mode_num_delayed_payment)
df['Num_Credit_Inquiries'] = df['Num_Credit_Inquiries'].fillna(median_num_credit_inquiries)
df['Amount_invested_monthly'] = df['Amount_invested_monthly'].fillna(median_amount_invested_monthly)
df['Monthly_Balance'] = df['Monthly_Balance'].fillna(median_monthly_balance)
df['Annual_Income'] = df['Annual_Income'].fillna(median_annual_income)
df['Changed_Credit_Limit'] = df['Changed_Credit_Limit'].fillna(median_changed_credit_limit)
df['Outstanding_Debt'] = df['Outstanding_Debt'].fillna(median_outstanding_debt)
df['Credit_Utilization_Ratio'] = df['Credit_Utilization_Ratio'].fillna(median_credit_utilization_ratio)
df['Total_EMI_per_month'] = df['Total_EMI_per_month'].fillna(median_total_emi_per_month)
df['Num_of_Loan'] = df['Num_of_Loan'].fillna(median_num_of_loan)
df['Num_Bank_Accounts'] = df['Num_Bank_Accounts'].fillna(median_num_bank_accounts)
df['Num_Credit_Card'] = df['Num_Credit_Card'].fillna(median_num_credit_card)
df['Interest_Rate'] = df['Interest_Rate'].fillna(median_interest_rate)
df['Delay_from_due_date'] = df['Delay_from_due_date'].fillna(median_delay_from_due_date)

# Handle 'Payment_of_Min_Amount' separately: fill missing, then map
if 'Payment_of_Min_Amount' in df.columns:
    mode_payment_min_amount = df['Payment_of_Min_Amount'].mode()[0]
    df['Payment_of_Min_Amount'] = df['Payment_of_Min_Amount'].fillna(mode_payment_min_amount)
    df['Payment_of_Min_Amount'] = df['Payment_of_Min_Amount'].map({'No': 0, 'Yes': 1})
    # Ensure the column is numeric after mapping
    df['Payment_of_Min_Amount'] = pd.to_numeric(df['Payment_of_Min_Amount'], errors='coerce')


# Display the number of missing values for these columns after imputation
print(df[cols_to_clean_and_convert + ['Payment_of_Min_Amount']].isnull().sum())
print(df.isnull().sum())

# Identify categorical columns to encode
categorical_cols_to_encode = ['Month', 'Occupation', 'Credit_Mix', 'Payment_Behaviour']

# Perform one-hot encoding
df = pd.get_dummies(df, columns=categorical_cols_to_encode, drop_first=True)

# Display the first few rows and the columns of the updated DataFrame
display(df.head())
display(df.columns)

# Mapping the 'Credit_Score' column to numerical values
credit_score_mapping = {'Poor': 0, 'Standard': 1, 'Good': 2}
df['Credit_Score'] = df['Credit_Score'].map(credit_score_mapping)

# Displaying the value counts of the updated 'Credit_Score' column
display(df['Credit_Score'].value_counts())

"""# Exploratory Data Analysis (EDA)"""

# Visualizing Target Distribution ('Credit_Score')
plt.figure(figsize=(8, 6))
sns.countplot(data=df, x='Credit_Score')
plt.title('Credit Score Distribution')
plt.xlabel('Credit Score')
plt.ylabel('Count')
plt.show()

plt.figure(figsize = (10,6))
sns.boxplot(data = df, x = 'Credit_Score', y = 'Annual_Income')
plt.title('Annual Income vs Credit Score')
plt.xlabel('Credit Score')
plt.ylabel('Annual Income')
plt.xticks([0, 1, 2], ['Poor', 'Standard', 'Good'])
plt.show()

# Correlation Analysis of numerical columns
numerical_df = df.select_dtypes(include=np.number)

correlation_matrix = numerical_df.corr()

plt.figure(figsize = (16,12))
sns.heatmap(correlation_matrix, annot = True, cmap='coolwarm')
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""# Feature Engineering"""

# Creating 'Total_Number_of_Accounts' feature
df['Total_Number_of_Accounts'] = df['Num_Bank_Accounts'] + df['Num_Credit_Card']
display(df[['Num_Bank_Accounts', 'Num_Credit_Card', 'Total_Number_of_Accounts']].head())

# Creating 'Payment to Income Ratio' feature
# Adding a small epsilon to the denominator to avoid division by zero, although describe shows min > 0
df['Payment_to_Income_Ratio'] = df['Total_EMI_per_month'] / (df['Monthly_Inhand_Salary'] + 1e-6)
display(df[['Total_EMI_per_month', 'Monthly_Inhand_Salary', 'Payment_to_Income_Ratio']].head())

"""# Train-Test Split"""

# Create a new DataFrame X by dropping the 'Credit_Score' column
X = df.drop('Credit_Score', axis=1)

# Create a new Series y containing only the 'Credit_Score' column
y = df['Credit_Score']

# Display the first five rows of X
display(X.head())

# Display the first five rows of y
display(y.head())

"""# Standardization"""

from sklearn.preprocessing import StandardScaler

# Identify numeric columns to standardize (excluding binary and one-hot encoded columns)
numeric_cols_to_standardize = ['Age', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts',
                               'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Delay_from_due_date',
                               'Num_of_Delayed_Payment', 'Num_Credit_Inquiries', 'Outstanding_Debt',
                               'Credit_Utilization_Ratio', 'Credit_History_Age', 'Total_EMI_per_month',
                               'Amount_invested_monthly', 'Monthly_Balance', 'Changed_Credit_Limit', 'Payment_of_Min_Amount', 'Total_Number_of_Accounts', 'Payment_to_Income_Ratio']

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and testing data
X_train[numeric_cols_to_standardize] = scaler.fit_transform(X_train[numeric_cols_to_standardize])
X_test[numeric_cols_to_standardize] = scaler.transform(X_test[numeric_cols_to_standardize])

# Display the first few rows of the standardized DataFrames
print("\nStandardized X_train:")
display(X_train.head())
print("\nStandardized X_test:")
display(X_test.head())

"""# Training the Dataset"""

# Impute remaining missing values with the median in X_train and X_test
for col in X_train.columns:
    if X_train[col].isnull().any():
        median_val = X_train[col].median()
        X_train[col] = X_train[col].fillna(median_val)
        # Impute X_test using the median calculated from X_train
        if col in X_test.columns:
            X_test[col] = X_test[col].fillna(median_val)

# Verify that there are no more missing values
print("NaN values in X_train after imputation:")
display(X_train.isnull().sum().sum())

print("\nNaN values in X_test after imputation:")
display(X_test.isnull().sum().sum())

# Impute missing values in y_train and y_test with the mode of y_train
mode_y_train = y_train.mode()[0]
y_train = y_train.fillna(mode_y_train)
y_test = y_test.fillna(mode_y_train)

# Verify that there are no more missing values in y_train and y_test
print("NaN values in y_train after imputation:")
display(y_train.isnull().sum())

print("\nNaN values in y_test after imputation:")
display(y_test.isnull().sum())

# Training on Logistic Regression Model
log_reg = LogisticRegression(random_state=42)
log_reg.fit(X_train, y_train)

# tTraining on Decission Tree Classifier
dt_clf = DecisionTreeClassifier(random_state=42)
dt_clf.fit(X_train, y_train)

# Training on Random Forest Classifier
rf_clf = RandomForestClassifier(random_state=42)
rf_clf.fit(X_train, y_train)

print("Models trained successfully.")

"""# Model Evaluation"""

# Predictions on the test data
y_pred_log_reg = log_reg.predict(X_test)
y_pred_dt_clf = dt_clf.predict(X_test)
y_pred_rf_clf = rf_clf.predict(X_test)

# Logistic Regression Evaluation
print('Logistic Regression Evaluation:')
print('Accuracy:', accuracy_score(y_test, y_pred_log_reg))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred_log_reg))
print('Classification Report:\n', classification_report(y_test, y_pred_log_reg))
print('-'* 55)

# Decision Tree Classifier Evaluation
print('Decision Tree Classifier Evaluation:')
print('Accuracy:', accuracy_score(y_test, y_pred_dt_clf))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred_dt_clf))
print('Classification Report:\n', classification_report(y_test, y_pred_dt_clf))
print('-'* 55)

# Random Forest Classifier Evaluation
print('Random Forest Classifier Evaluation:')
print('Accuracy:', accuracy_score(y_test, y_pred_rf_clf))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred_rf_clf))
print('Classification Report:\n', classification_report(y_test, y_pred_rf_clf))

"""# Hyperparameter Tuning (Random Forest)"""

from sklearn.model_selection import RandomizedSearchCV

# Define the parameter grid for RandomizedSearchCV
param_grid = {
    'n_estimators': [100, 200, 300],  # Number of trees in the forest
    'max_features': ['sqrt', 'log2'],  # Number of features to consider at every split
    'max_depth': [10, 20, 30, None],  # Maximum number of levels in tree
    'min_samples_split': [2, 5, 10],  # Minimum number of samples required to split a node
    'min_samples_leaf': [1, 2, 4],  # Minimum number of samples required at each leaf node
    'bootstrap': [True, False] # Method of selecting samples for training each tree
}

# Initialize RandomizedSearchCV
# We'll use n_iter=50 for a reasonable number of iterations, but this can be adjusted
rf_random = RandomizedSearchCV(estimator=rf_clf, param_distributions=param_grid,
                               n_iter=50, cv=3, verbose=2, random_state=42, n_jobs=-1)

# Fit the random search model
rf_random.fit(X_train, y_train)

"""# Evaluate Tuned Random Forest Model"""

# Get the best model from the random search
best_rf_clf = rf_random.best_estimator_

# Make predictions with the best model
y_pred_best_rf = best_rf_clf.predict(X_test)

# Evaluate the best model
print("Tuned Random Forest Classifier Evaluation:")
print("Accuracy:", accuracy_score(y_test, y_pred_best_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_best_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_best_rf))