# -*- coding: utf-8 -*-
"""Handwritten_Character_Recognition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KURQqMHhPzTm8Hnxvv6CneYtiB_QN9of

# Importing Libraries
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.utils import to_categorical

"""# Loading Dataset"""

(X_train, y_train), (X_test, y_test) = mnist.load_data()
print("Training Samples:", X_train.shape[0])
print("Testing Samples:", X_test.shape[0])

"""# Preprocessing"""

# Normalize pixel values
X_train = X_train.astype('float32')/255.0
X_test = X_test.astype('float32')/255.0

# Reshape the input data
X_train = X_train.reshape(-1, 28, 28, 1)
X_test = X_test.reshape(-1, 28, 28, 1)

# One-hot encode labels
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

print("Shape after Preprocessing:", X_train.shape)

"""# Building CNN Model"""

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(10, activation='softmax')
])

model.summary()

"""# Compile and Train Model"""

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

history = model.fit(
    X_train, y_train,
    batch_size=128,
    epochs=10,
    validation_split=0.2,
    verbose=1
)

"""# Visualize Training Progress"""

plt.figure(figsize=(8,5))
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy Over Epochs')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

"""# Evaluate on Test Set"""

test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {test_accuracy * 100:2f}%')

"""# Prediction on New Image"""

# Prediction on a random test image
index = np.random.randint(0, len(X_test))
sample = X_test[index].reshape(1,28,28,1)

pred = np.argmax(model.predict(sample))
actual = np.argmax(y_test[index])

plt.imshow(X_test[index].reshape(28,28), cmap='gray')
plt.title(f"Predicted: {pred}, Actual: {actual}")
plt.show()