# -*- coding: utf-8 -*-
"""Emotion_Recognition_from_Speech

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVC-F96bz1SxsbSWMIJxSNUD59uxTkfP

# Importing Libraries
"""

import zipfile
import librosa
import soundfile
import numpy as np
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, GRU, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.models import load_model
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm

"""# Loading Dataset"""

from google.colab import drive
drive.mount('/content/drive')

zip_path = "/content/drive/MyDrive/RAVDESS.zip"  # change path if needed
extracted_path = "/content/RAVDESS"

# Extract zip
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extracted_path)

print("Files extracted to:", extracted_path)

"""# Feature Extraction (MFCC)"""

def extract_features(file):
    try:
        with soundfile.SoundFile(file) as sound:
            X_audio = sound.read(dtype='float32')
            sample_rate = sound.samplerate

            # Convert stereo → mono
            if X_audio.ndim > 1:
                X_audio = librosa.to_mono(X_audio.T)

            # Skip empty or short clips
            if len(X_audio) < 2048:
                print(f"Skipping {file}: too short ({len(X_audio)} samples).")
                return None

            # Handle silence (low energy)
            if np.sum(np.abs(X_audio)) < 0.01:
                print(f"Skipping {file}: almost silent.")
                return None

            # Extract STFT safely
            n_fft = min(2048, len(X_audio))  # Prevents warning
            stft = np.abs(librosa.stft(X_audio, n_fft=n_fft))

            # Feature extraction
            mfccs = np.mean(librosa.feature.mfcc(y=X_audio, sr=sample_rate, n_mfcc=40).T, axis=0)
            chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T, axis=0)
            mel = np.mean(librosa.feature.melspectrogram(y=X_audio, sr=sample_rate).T, axis=0)
            contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T, axis=0)

            # Combine
            features = np.hstack([mfccs, chroma, mel, contrast])
            return features

    except Exception as e:
        print(f"Error processing {file}: {e}")
        return None

"""# Build Dataset"""

emotions = {
    '01': 'neutral', '02': 'calm', '03': 'happy', '04': 'sad',
    '05': 'angry', '06': 'fearful', '07': 'disgust', '08': 'surprised'
}

X,y = [],[]

features_list = []

for subdir, dirs, files in os.walk(extracted_path):
    for file in tqdm(files):
        if file.endswith(".wav"):
            file_path = os.path.join(subdir, file)
            file_name = os.path.basename(file)
            emotion_code = file_name.split("-")[2]
            emotion = emotions.get(emotion_code)

            # Extract features
            features = extract_features(file_path)
            features = [f for f in features if f is not None]

            # Append
            features_list.append([features, emotion])

X, Y = zip(*features_list)
X = np.array(X)
Y = np.array(Y)

print("Feature shape:", X.shape)
print("Labels shape:", Y.shape)

df = pd.DataFrame(X)
df['emotion'] = Y
df.to_csv("ravdess_features.csv", index=False)
print("Features saved as ravdess_features.csv")

data = pd.read_csv("ravdess_features.csv")
data.head()

"""# Train/Test Split"""

X = data.drop('emotion', axis=1)
Y = data['emotion']

# Normalize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Encode labels
encoder = LabelEncoder()
Y_encoded = encoder.fit_transform(Y)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, Y_encoded, test_size=0.2, random_state=42)

"""# LSTM Model Building"""

model = Sequential([
    LSTM(256, return_sequences=False, input_shape=(X_train.shape[1], 1)),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(8, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

history = model.fit(X_train, y_train, validation_data=(X_test, y_test), batch_size=32, epochs=300)

"""# Model Evaluation"""

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")

y_pred = np.argmax(model.predict(X_test), axis=1)
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=encoder.classes_))

plt.figure(figsize=(10, 8))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues', xticklabels=encoder.classes_, yticklabels=encoder.classes_)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

"""# Visualize Training History"""

# Plot training & validation accuracy values
plt.figure(figsize=(12, 6))
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

# Plot training & validation loss values
plt.figure(figsize=(12, 6))
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

model.save("emotion_recognition_model.keras")

"""# Prediction on new Audio"""

test_audio = "/content/RAVDESS/Actor_01/03-01-03-01-01-01-01.wav"
file = test_audio
feature = extract_features(file).reshape(1, -1, 1)
prediction = model.predict(feature)
emotion = encoder.inverse_transform([np.argmax(prediction)])[0]
print("Predicted Emotion:", emotion)